"""Stub file for 'fitz' module with type hints."""

from typing import Any

def open(filename: str) -> Any: ...

class Document:
    def __len__(self) -> int: ...
    def __getitem__(self, key: int) -> Any: ...
    def close(self) -> None: ...

class FileDataError(Exception): ...
class FileNotFoundError(Exception): ...
